---
- name: create docker build dir
  file: state=directory path={{ logstash_docker_build }}

# we don't have rsync for photon yet, so use copy.
# copy doesn't have exclude and fails on the .git dir, so
# we use the with_fileglob to avoid getting .git
- name: sync the docker image src to remote nodes
  copy: src={{ item }} dest={{ logstash_docker_build }} mode=755
  with_fileglob:
    - ../../../../containers/docker/logstash-server/*


- name: build the image
  shell: cd {{ logstash_docker_build }} && /bin/bash ./build.sh

- name: docker run logstash server
  docker:
    docker_api_version: "{{ docker_api_version }}"
    name: logstash
    image: "{{ logstash_docker_image }}"
    memory_limit: "{{ memory_limit }}"
    restart_policy: always
    state: reloaded
    command: /start.sh -tags testingtag
#    env:
#      SERVICE_CHECK_SCRIPT: timeout 1 cat < /dev/null > /dev/tcp/$SERVICE_IP/$SERVICE_PORT
    expose:
      #- "{{ logstash_server_port }}/udp"
      - "{{ logstash_server_port }}/tcp"
    ports:
      #- "{{ logstash_container_port }}:{{ logstash_server_port }}/udp"
      - "{{ logstash_container_port }}:{{ logstash_server_port }}/tcp"
#    volumes:
#      - "{{ logstash_mapped_dir }}:/config-dir"
